/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clase;

import javax.swing.JOptionPane;

/**
 *
 * @author oscar
 */
public class Productos extends javax.swing.JFrame {

    /**
     * Creates new form Productos
     */
    public Productos() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblUnidades = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lblSubTotal = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        cbxCategorias = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        cbxCarnes = new javax.swing.JComboBox<>();
        cbxAbarrotes = new javax.swing.JComboBox<>();
        cbxCarnesFrias = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        cbxDescuentos = new javax.swing.JComboBox<>();
        cbxIva = new javax.swing.JComboBox<>();
        cbxUnidades = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        archivo = new javax.swing.JMenu();
        mnuAgregar = new javax.swing.JMenuItem();
        mnuComprar = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(50, 100));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 266, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_END);

        jPanel2.setPreferredSize(new java.awt.Dimension(400, 300));
        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        jPanel11.setPreferredSize(new java.awt.Dimension(229, 250));
        jPanel11.setLayout(new java.awt.GridLayout(3, 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Tipo de producto");
        jPanel11.add(jLabel1);

        lblTipo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel11.add(lblTipo);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Descripcion del producto");
        jPanel11.add(jLabel4);

        lblDescripcion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDescripcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel11.add(lblDescripcion);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Descuestos o unidades");
        jPanel11.add(jLabel5);

        lblUnidades.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUnidades.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel11.add(lblUnidades);

        jPanel2.add(jPanel11);

        jPanel12.setPreferredSize(new java.awt.Dimension(229, 250));
        jPanel12.setLayout(new java.awt.GridLayout(4, 2));

        jLabel2.setText("Precio");
        jPanel12.add(jLabel2);

        txtPrecio.setEnabled(false);
        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });
        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });
        jPanel12.add(txtPrecio);

        jLabel7.setText("Unidad o peso");
        jPanel12.add(jLabel7);

        txtPeso.setEnabled(false);
        txtPeso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPesoKeyTyped(evt);
            }
        });
        jPanel12.add(txtPeso);

        jLabel6.setText("Subtotal");
        jPanel12.add(jLabel6);
        jPanel12.add(lblSubTotal);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 146, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );

        jPanel12.add(jPanel13);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 146, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );

        jPanel12.add(jPanel14);

        jPanel2.add(jPanel12);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setPreferredSize(new java.awt.Dimension(400, 150));
        jPanel3.setLayout(new java.awt.GridLayout(1, 3));

        jPanel6.setLayout(new java.awt.GridLayout(3, 1));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 228, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel9);

        cbxCategorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elige un producto", "Carnes", "Abarrotes", "Carnes Frias" }));
        cbxCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCategoriasActionPerformed(evt);
            }
        });
        jPanel6.add(cbxCategorias);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 228, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel10);

        jPanel3.add(jPanel6);

        jPanel7.setLayout(new java.awt.GridLayout(3, 1));

        cbxCarnes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Res", "Puerco", "Pollo", "Pescado" }));
        cbxCarnes.setEnabled(false);
        jPanel7.add(cbxCarnes);

        cbxAbarrotes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Azucar", "Sal", "Harina", "Huevo" }));
        cbxAbarrotes.setEnabled(false);
        jPanel7.add(cbxAbarrotes);

        cbxCarnesFrias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jamon", "Salchicha", "Queso de puerco", "Chuleta" }));
        cbxCarnesFrias.setEnabled(false);
        jPanel7.add(cbxCarnesFrias);

        jPanel3.add(jPanel7);

        jPanel8.setLayout(new java.awt.GridLayout(3, 1));

        cbxDescuentos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5%", "10%", "15%" }));
        cbxDescuentos.setEnabled(false);
        jPanel8.add(cbxDescuentos);

        cbxIva.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12%", "16%", "20%" }));
        cbxIva.setEnabled(false);
        jPanel8.add(cbxIva);

        cbxUnidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pieza", "kilogramo", "Gramos" }));
        cbxUnidades.setEnabled(false);
        jPanel8.add(cbxUnidades);

        jPanel3.add(jPanel8);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel5.setMinimumSize(new java.awt.Dimension(100, 30));
        jPanel5.setPreferredSize(new java.awt.Dimension(400, 30));
        jPanel5.setLayout(new java.awt.GridLayout(1, 1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ABARROTES \"EL MIJE SA DE CV\"");
        jPanel5.add(jLabel3);

        getContentPane().add(jPanel5, java.awt.BorderLayout.PAGE_END);

        jPanel4.setPreferredSize(new java.awt.Dimension(50, 100));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 266, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_START);

        archivo.setText("Archivo");

        mnuAgregar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mnuAgregar.setText("Agregar");
        mnuAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAgregarActionPerformed(evt);
            }
        });
        archivo.add(mnuAgregar);

        mnuComprar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mnuComprar.setText("Comprar");
        mnuComprar.setEnabled(false);
        mnuComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuComprarActionPerformed(evt);
            }
        });
        archivo.add(mnuComprar);

        mnuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mnuSalir.setForeground(new java.awt.Color(255, 51, 51));
        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        archivo.add(mnuSalir);

        jMenuBar1.add(archivo);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCategoriasActionPerformed
        // TODO add your handling code here:
        if (cbxCategorias.getSelectedItem() == "Carnes") {
            cbxCarnes.setEnabled(true);
            cbxAbarrotes.setEnabled(false);
            cbxCarnesFrias.setEnabled(false);
            cbxDescuentos.setEnabled(true);
            cbxIva.setEnabled(false);
            cbxUnidades.setEnabled(false);

        }
        if (cbxCategorias.getSelectedItem() == "Abarrotes") {
            cbxCarnes.setEnabled(false);
            cbxAbarrotes.setEnabled(true);
            cbxCarnesFrias.setEnabled(false);
            cbxDescuentos.setEnabled(false);
            cbxIva.setEnabled(true);
            cbxUnidades.setEnabled(false);

        }
        if (cbxCategorias.getSelectedItem() == "Carnes Frias") {
            cbxCarnes.setEnabled(false);
            cbxAbarrotes.setEnabled(false);
            cbxCarnesFrias.setEnabled(true);
            cbxDescuentos.setEnabled(false);
            cbxIva.setEnabled(false);
            cbxUnidades.setEnabled(true);

        }
    }//GEN-LAST:event_cbxCategoriasActionPerformed

    private void mnuAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAgregarActionPerformed
        // TODO add your handling code here:
        if (cbxCategorias.getSelectedItem() == "Elige un producto") {
            JOptionPane.showMessageDialog(null, "Elige un producto de la categoria");
        } else {
            if (cbxCategorias.getSelectedItem() == "Carnes") {
                String Tipo = (String) cbxCategorias.getSelectedItem();
                lblTipo.setText(Tipo);
                String Carnes = (String) cbxCarnes.getSelectedItem();
                lblDescripcion.setText(Carnes);
                String des = (String) cbxDescuentos.getSelectedItem();
                lblUnidades.setText(des);
                mnuComprar.setEnabled(true);
                txtPrecio.setEnabled(true);
                mnuAgregar.setEnabled(false);
            }
            if (cbxCategorias.getSelectedItem() == "Abarrotes") {
                String Tipo = (String) cbxCategorias.getSelectedItem();
                lblTipo.setText(Tipo);
                String Aba = (String) cbxAbarrotes.getSelectedItem();
                lblDescripcion.setText(Aba);
                String iva = (String) cbxIva.getSelectedItem();
                lblUnidades.setText(iva);
                mnuComprar.setEnabled(true);
                txtPrecio.setEnabled(true);
                mnuAgregar.setEnabled(false);
            }
            if (cbxCategorias.getSelectedItem() == "Carnes Frias") {
                String Tipo = (String) cbxCategorias.getSelectedItem();
                lblTipo.setText(Tipo);
                String frias = (String) cbxCarnesFrias.getSelectedItem();
                lblDescripcion.setText(frias);
                String uni = (String) cbxUnidades.getSelectedItem();
                lblUnidades.setText(uni);
                mnuComprar.setEnabled(true);
                txtPrecio.setEnabled(true);
                mnuAgregar.setEnabled(false);
                 txtPeso.setEnabled(true);

            }
        }


    }//GEN-LAST:event_mnuAgregarActionPerformed

    private void mnuComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuComprarActionPerformed
        // TODO add your handling code here:

        if (txtPrecio.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingresa el precio del producto");
        } else {
            if (cbxCategorias.getSelectedItem() == "Carnes") {
                int precio = Integer.parseInt(txtPrecio.getText());
                String des = (String) cbxDescuentos.getSelectedItem();
                String Des = des.substring(0, des.length() - 1);
                float sub = precio - (precio * (Float.parseFloat(Des) / 100));
                lblSubTotal.setText(Float.toString(sub));
            }
            if (cbxCategorias.getSelectedItem() == "Abarrotes") {
                int precio = Integer.parseInt(txtPrecio.getText());
                String des = (String) cbxIva.getSelectedItem();
                String Des = des.substring(0, des.length() - 1);
                float sub = precio + (precio * (Float.parseFloat(Des) / 100));
                lblSubTotal.setText(Float.toString(sub));
            }
            if (cbxCategorias.getSelectedItem() == "Carnes Frias") {
                if (txtPeso.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Agrega una cantidad o peso del producto");
                } else {
                    int precio = Integer.parseInt(txtPrecio.getText());
                    String des = (String) cbxUnidades.getSelectedItem();
                    float peso = Float.parseFloat(txtPeso.getText());
                    float sub = precio * peso;
                    lblSubTotal.setText(Float.toString(sub));

                }
            }
        }
    }//GEN-LAST:event_mnuComprarActionPerformed

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped
        // TODO add your handling code here:
        if ((evt.getKeyChar() >= 48) && (evt.getKeyChar() <= 57) || (evt.getKeyChar() == 8)) {

        } else {
            evt.consume();
            JOptionPane.showMessageDialog(null, "No todos son numeros", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtPrecioKeyTyped

    private void txtPesoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesoKeyPressed
    
    }//GEN-LAST:event_txtPesoKeyPressed

    private void txtPesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesoKeyTyped
        // TODO add your handling code here:
        if ((evt.getKeyChar() >= 48) && (evt.getKeyChar() <= 57) || (evt.getKeyChar() == 8)) {

        } else {
            evt.consume();
            JOptionPane.showMessageDialog(null, "No todos son numeros", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtPesoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu archivo;
    private javax.swing.JComboBox<String> cbxAbarrotes;
    private javax.swing.JComboBox<String> cbxCarnes;
    private javax.swing.JComboBox<String> cbxCarnesFrias;
    private javax.swing.JComboBox<String> cbxCategorias;
    private javax.swing.JComboBox<String> cbxDescuentos;
    private javax.swing.JComboBox<String> cbxIva;
    private javax.swing.JComboBox<String> cbxUnidades;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblSubTotal;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblUnidades;
    private javax.swing.JMenuItem mnuAgregar;
    private javax.swing.JMenuItem mnuComprar;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
